### PR TITLE
Update _config.yml

### PR DESCRIPTION
**Pull request by JaneRuby**

### CODE REVIEW

**Comment by ShikherVerma** [comment]
@JaneRuby you have to fork this repo and make pull requests to your `master` branch not mine :P

**Comment by JaneRuby** [comment]
i thought i did that?
 how do i fix it? I'm sorry! It's for a class project!

**Comment by ShikherVerma** [comment]
When you make the pull request you will have an option to change the branch
to which the pull request is to. Basically you will see ShikherVerma/master
chance it to janeruby/master.

**Comment by JaneRuby** [comment]
I am embarrassed to say that I do not know to to fix this. Can you just
undo it? Or what specifically do I need to do to fix this???

**Comment by ShikherVerma** [comment]
Its fine. Github doesn't allow delete/undo on pull requests so I just have to leave it in closed state (which it already is). 
Are you trying to setup your website with [CleanBlogEnhanced Theme](https://github.com/ShikherVerma/Shikherverma.github.io) ? I could help you with that, in return you could write a guest post for my blog about how you setup this theme and change content. I have been wanting to write a blog on that.

**Comment by JaneRuby** [comment]
Hi,

Yes I was. I really liked the format. I apologize for messing everything
up, but yes if you could help me, I would be more than happy to write a
guest post for you!

**Comment by ShikherVerma** [comment]
please contact me on facebook. Chatting on pull request isn't really convenient. Also everything is visible on https://github.com/ShikherVerma/Shikherverma.github.io/pull/1

**Comment by JaneRuby** [comment]
I'm Jane Ruby Sky on FB. Sounds good!

**Pull request closed without merging**
